spring:
  datasource:
    url: jdbc:h2:mem:desafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
logging:
  level:
    root: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
app:
  csv:
    path: csv/movielist-no-tie.csv
